words = [
    ("erode", "aşındırmak"),
    ("contamination", "kirlenme"),
    ("cultivation", "toprağı işleme"),
    ("deforestation", "ormansızlaştırma"),
    ("devastation", "yıkım"),
    ("drought", "kuraklık"),
    ("fertiliser", "gübre"),
    ("flood", "sel basmak"),
    ("pollutant", "kirlilik"),
    ("reforestation", "yeniden ağaçlandırma"),
    ("soil", "toprak"),
    ("arid", "kurak"),
    ("catastrophe", "felaket"),
    ("contaminated", "kirlenmiş"),
    ("depleted", "tükenmiş"),
    ("devastating", "yıkıcı"),
    ("disposable", "tek kullanımlık"),
    ("hazardous", "tehlikeli"),
    ("renewable", "sürdürülebilir"),
    ("exhaust fumes", "egzoz dumanı"),
    ("decompose", "ayrışmak"),
    ("hibernate", "kış uykusuna yatmak"),
    ("poach", "kaçak avlanmak"),
    ("prey on", "avlanmak"),
    ("predator", "yırtıcı hayvan"),
    ("prey", "av, kurban"),
    ("extinct", "yok olmak"),
    ("extinct", "nesli tükenmiş"),
    ("unspoilt", "bozulmamış"),
    ("reserve", "yer ayırmak, tahsis etmek"),
    ("accompany", "eşlik etmek"),
    ("cater for", "ihtiyacını karşılamak"),
    ("disembark from", "bir yerden inmek"),
    ("embark", "(gemiye) binmek"),
    ("hitchhike", "otostop çekmek"),
    ("amenities", "konaklama"),
    ("attraction", "varış"),
    ("excursion", "gezi"),
    ("expedition", "sefer"),
    ("facilities", "tesisler"),
    ("hospitality", "misafirperverlik"),
    ("itinerary", "seyahat programı"),
    ("landmark", "dönüm noktası"),
    ("supplies", "tedarik"),
    ("coastal", "kıyı"),
    ("hospitable", "misafirperver"),
    ("depict", "tasvir etmek"),
    ("display", "görüntülemek"),
    ("exhibit", "sergilemek"),
    ("ancestor", "ata"),
    ("audience", "seyirci"),
    ("depiction", "tasvir"),
    ("excavation", "kazı"),
    ("exhibition", "sergi"),
    ("genre", "tür"),
    ("legacy", "miras"),
    ("venue", "mekan"),
    ("captivating", "büyüleyici"),
    ("influential", "etkili, etkileyici"),
    ("mundane", "sıradan"),
    ("vivid", "canlı, parlak"),
    ("preserve", "korumak, muhafaza etmek"),
    ("vanish", "ortadan kaybolmak"),
    ("aspect", "taraf"),
    ("boundary", "sınır"),
    ("reluctant", "isteksiz"),
    ("discard", "atmak"),
    ("dispose", "elden çıkarmak"),
    ("dump", "çöplük"),
    ("preserve", "korumak"),
    ("conservation", "koruma"),
    ("emission", "emisyon"),
    ("field", "alan"),
    ("landfill", "çöp sahası"),
    ("pesticide", "pestisit"),
    ("preservation", "koruma"),
    ("biodegradable", "biyolojik olarak parçalanan"),
    ("disastrous", "felaket"),
    ("devour", "yutmak"),
    ("reproduce", "yeniden üretmek"),
    ("biodiversity", "biyolojik çeşitlilik"),
    ("depart from", "ayrılmak"),
    ("departure", "kalkış"),
    ("fare", "bilet ücreti"),
    ("idyllic", "cennet gibi, huzurlu"),
    ("picturesque", "resmedilmeye değer"),
    ("inspire", "ilham vermek"),
    ("portray", "canlandırmak"),
    ("artefact", "eser"),
    ("conception of", "anlayış"),
    ("era", "çağ"),
    ("heritage", "miras"),
    ("inspiration", "ilham"),
    ("prehistoric", "tarih öncesi"),
    ("prominent", "öne çıkan"),
    ("on display", "sergilemek, göstermek"),
    ("make arrangements", "düzenlemeler yapmak"),
    ("intellectual", "zihinsel, akla dayanan"),
    ("conserve", "korumak"),
    ("contaminate", "kirletmek"),
    ("cultivate", "yetiştirmek"),
    ("devastate", "harap etmek"),
    ("emit", "yaymak"),
    ("pollute", "kirletmek"),
    ("voyage", "yolculuk"),
    ("intercept", "yolunu kesmek, durdurmak"),
    ("myriad", "sayısız, çok"),
    ("nutrient", "besin, gıda"),
    ("terrestrial", "karasal"),
    ("vegetation", "bitki örtüsü"),
    ("breed", "cins"),
    ("diurnal", "günlük"),
    ("endure", "katlanmak"),
    ("obscure", "belirsiz"),
    ("stray", "başıboş"),
    ("accumulate", "biriktirmek"),
    ("adapt", "uyum"),
    ("sparse", "seyrek"),
    ("stressor", "strese neden olan"),
    ("thrive", "gelişmek, büyümek"),
    ("transitional", "geçiş, geçici"),
    ("violent", "şiddetli"),
    ("anticipate", "tahmin etmek"),
    ("demonstrate", "göstermek"),
    ("distracting", "dikkat dağıtıcı"),
    ("indiscernible", "ayırt edilemez"),
    ("peripheral nervous system", "çevresel sinir sistemi"),
    ("unconsciously", "bilinçsizce"),
    ("entertainment", "eğlence"),
    ("exhibit", "sergilemek"),
    ("grandeur", "görkem, ihtişam"),
    ("remnant", "kalıntı"),
    ("renovation", "yenileme"),
    ("spectator", "seyirci"),
    ("chunk", "yığın"),
    ("crucial", "çok önemli"),
    ("engage", "uğraşmak, ilgilenmek, meşgul olmak"),
    ("overwhelming", "baskın, karşı konulamaz"),
    ("rejuvenate", "gençleştirmek, canlandırmak"),
    ("suffer", "acı çekmek"),
    ("exile", "sürgün"),
    ("prosper", "zenginleşmek"),
    ("regulate", "düzenlemek"),
    ("subsidies", "mali destek sağlamak"),
    ("diversity of", "birçok farklı"),
    ("famine", "kıtlık"),
    ("infrastructure", "altyapı"),
    ("outcast", "toplumdışı kişi"),
    ("poverty", "yoksulluk"),
    ("prosperity", "refah, zenginlik"),
    ("subsidy", "devlet desteği"),
    ("altruism", "fedakârlık"),
    ("fundraiser", "bağış toplayan kişi, etkinlik veya kuruluş"),
    ("philanthropy", "hayırseverlik"),
    ("charitable", "hayırsever"),
    ("congestion", "sıkışıklık, tıkanıklık"),
    ("dwelling", "konut"),
    ("property", "mal, mülk"),
    ("slum", "gecekondu"),
    ("diverse", "çeşitli"),
    ("aid", "yardım"),
    ("construct", "inşa etmek"),
    ("renovate", "yenilemek"),
    ("district", "bölge"),
    ("tenancy", "kiracılık"),
    ("suburban", "kenar mahalle"),
    ("urban", "kentsel"),
    ("alienate", "yabancılaştırmak"),
    ("degrade", "aşağılamak"),
    ("deport", "sınır dışı etmek"),
    ("discriminate", "ayrımcılık yapmak"),
    ("immigration", "göç"),
    ("integrate", "birleştirmek"),
    ("marginalise", "ötekileştirmek"),
    ("migrate from", "...dan göçmek"),
    ("settle in", "yerleşmek"),
    ("degradation", "bozulma"),
    ("emigrant", "göçmen"),
    ("minority", "azınlık"),
    ("prejudice", "önyargı"),
    ("refugee", "mülteci"),
    ("destitute", "muhtaç"),
    ("assert", "ileri sürmek, iddia etmek"),
    ("clarify", "açıklamak"),
    ("hesitate", "tereddüt etmek"),
    ("imply", "ima etmek"),
    ("infer from", "sonuç çıkarmak"),
    ("insult", "hakaret etmek"),
    ("pronounce", "telaffuz etmek"),
    ("refer to", "bahsetmek, göndermek"),
    ("respond", "yanıtlamak"),
    ("assertiveness", "kendine güven"),
    ("clarification", "açıklama"),
    ("dialect", "lehçe"),
    ("gesture", "jest, mimik"),
    ("hesitation", "tereddüt"),
    ("accuracy", "doğruluk, kesinlik"),
    ("inference", "çıkarım"),
    ("interpretation", "yorum"),
    ("offence", "suç"),
    ("rumours", "söylenti"),
    ("assertive", "iddialı"),
    ("expressive", "anlamlı"),
    ("extroverted", "dışa dönük"),
    ("hesitant", "tereddütlü"),
    ("implied", "ima edilen"),
    ("acquaint", "tanımak, bilmek"),
    ("bond", "bağ, ilişki"),
    ("descend from", "soyundan gelmek"),
    ("foster", "büyütmek, geliştirmek"),
    ("inherit", "miras almak"),
    ("interfere", "müdahale etmek"),
    ("propose to", "teklif etmek"),
    ("resemble", "benzemek"),
    ("acquaintance", "tanıdık"),
    ("affection", "sevgi, şefkat"),
    ("ancestor", "ata, soy"),
    ("conflict", "çatışma, anlaşmazlık"),
    ("descendant", "soyundan gelen kimse"),
    ("spouse", "eş"),
    ("drawback", "dezavantaj"),
    ("equip", "donatmak"),
    ("freight", "nakliye"),
    ("intense", "yoğun"),
    ("knot", "düğüm"),
    ("rugged", "engebeli"),
    ("stringent", "sıkı, katı"),
    ("tricky", "zor, güç"),
    ("vulnerable", "hassas, savunmasız"),
    ("clog", "tıkamak"),
    ("destruction", "yıkım"),
    ("disruptive", "yıkıcı, bozucu"),
    ("intrinsic", "asıl, hakiki"),
    ("pedestrian", "yaya"),
    ("release", "serbest bırakmak"),
    ("rival", "rakip"),
    ("shield", "kalkan"),
    ("vent", "delik, yarık"),
    ("accelerate", "hızlandırmak"),
    ("appeal", "cezbetmek, başvuruda bulunmak"),
    ("commuter", "ev ile iş arasında gidip gelen"),
    ("consume", "tüketmek"),
    ("flair", "yetenek"),
    ("hamper", "engellemek"),
    ("incentive", "teşvik"),
    ("monetary", "parasal"),
    ("plodding", "ağır, zahmetli iş"),
    ("rural", "kırsal"),
    ("span", "sürmek, kapsamak"),
    ("sprawl", "yayılmak"),
    ("culminate", "sonuçlanmak"),
    ("exaggerate", "abartmak"),
    ("frailty", "zaaf, zayıflık"),
    ("merge", "birleştirmek"),
    ("portray", "betimlemek"),
    ("prominent", "öne çıkan"),
    ("prop", "desteklemek"),
    ("reminiscent", "hatırlatan"),
    ("acquainted", "tanışık, bilinen"),
    ("affectionate", "sevecen"),
    ("committed", "kendini adamış"),
    ("dependent", "bağımlı"),
    ("dysfunctional", "işlevsiz"),
    ("separated", "ayrılmış"),
    ("nurture", "bakmak, beslemek"),
    ("punish", "cezalandırmak"),
    ("raise", "artırmak, yükseltmek"),
    ("rear", "arka"),
    ("adolescence", "ergenlik"),
    ("cognition", "kavrama, bilişsellik"),
    ("infancy", "bebeklik"),
    ("infant", "bebek"),
    ("juvenile", "genç, çocuksu"),
    ("maturity", "olgunluk"),
    ("punishment", "ceza"),
    ("upbringing", "yetiştirme, terbiye"),
    ("boisterous", "gürültücü"),
    ("cognitive", "bilişsel"),
    ("assess", "değerlendirmek"),
    ("assign to", "tahsis etmek, ayırmak, vermek"),
    ("assimilate", "özümsemek"),
    ("certify", "onaylamak"),
    ("comprehend", "anlamak, kavramak"),
    ("consolidate", "sağlamlaştırmak"),
    ("evaluate", "değerlendirmek"),
    ("examine", "incelemek"),
    ("expel", "kovmak"),
    ("revise", "gözden geçirmek"),
    ("transmit", "iletmek"),
    ("assessment", "değerlendirme"),
    ("inclination", "eğilim"),
    ("insight", "kavrama"),
    ("instruction", "talimat"),
    ("syllabus", "müfredat"),
    ("advance", "ilerlemek, gelişmek"),
    ("diligent", "çalışkan, gayretli"),
    ("illiterate", "cahil"),
    ("intellectual", "zihinsel, akla dayanan"),
    ("tertiary", "üçüncül"),
    ("resit", "tekrar sınava girmek"),
    ("attend", "katılmak"),
    ("enrol", "kaydolmak, yazılmak"),
    ("instruct", "talimat vermek"),
    ("administration", "yönetim"),
    ("advisor", "danışman"),
    ("counsellor", "danışman"),
    ("dissertation", "tez"),
    ("distinction", "ayrım, fark"),
    ("dormitory", "yurt, yatakhane"),
    ("freshmen", "birinci sınıf öğrencisi"),
    ("grant", "vermek, bağışlamak"),
    ("sophomore", "ikinci sınıf öğrencisi"),
    ("thesis", "tez"),
    ("tutor", "özel öğretmen"),
    ("appoint", "atamak"),
    ("aspire", "şiddetle arzu etmek, çok istemek"),
    ("commute", "ev ile iş arasında gidip gelmek"),
    ("delegate", "temsilci"),
    ("recruit", "işe almak"),
    ("candidate", "aday"),
    ("consultant", "danışman"),
    ("consultation", "danışma, görüşme"),
    ("dismal", "kasvetli, sıkıntılı"),
    ("incentive", "teşvik"),
    ("perks", "ikramiye"),
    ("occupation", "meslek"),
    ("recruitment", "işe alma"),
    ("redundancy", "fazlalık"),
    ("subordinate", "ikincil, daha az önemli"),
    ("vacancy", "açık kadro, boşluk"),
    ("workforce", "iş gücü"),
    ("aspiring", "hevesli"),
    ("capable", "yetenekli"),
    ("demanding", "zahmetli"),
    ("fulfilling", "tatmin edici"),
    ("export", "ihraç etmek"),
    ("assets", "varlıklar"),
    ("downsize", "küçültmek, azaltmak"),
    ("corporate", "kurumsal"),
    ("lucrative", "karlı, kazançlı"),
    ("firm", "sıkı, sağlam"),
    ("merchant", "tüccar"),
    ("niche", "yer, yuva, yaşam çentiği"),
    ("premises", "tesis, mülk"),
    ("profit", "kâr"),
    ("takeover", "devralma"),
    ("taxation", "vergilendirme"),
    ("turnover", "ciro"),
    ("booming", "gelişen"),
    ("quarterly", "üç ayda bir olan"),
    ("fund", "fon, sermaye"),
    ("plummet", "düşmek, azalmak"),
    ("remunerate", "ödüllendirmek, hakkını vermek"),
    ("withdraw", "geri çekilmek"),
    ("bargain", "pazarlık"),
    ("cheque", "çek")
]